# Spring config server configuration example
---
spring:
  cloud:
    config:
      server:
        git:
          uri: 
          searchPaths: 
        # "native" is used when the native profile is active, for local tests with a classpath repo:
        native:
          searchLocations: classpath:offline-repository/
server:
  port: 8001
  
---
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: default
eureka:
  instance:
    hostname: eurekahost 
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/